// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV2aaO45qelyp7CgCC1FZqO-DZl0RcRmg',
    appId: '1:292385856722:web:53fa352de820a85165610b',
    messagingSenderId: '292385856722',
    projectId: 'shopping-app-final-k23',
    authDomain: 'shopping-app-final-k23.firebaseapp.com',
    storageBucket: 'shopping-app-final-k23.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIyAPeLRpe9UvjgaXTtfNozgwnAnx_Aek',
    appId: '1:292385856722:android:0dffff941673afde65610b',
    messagingSenderId: '292385856722',
    projectId: 'shopping-app-final-k23',
    storageBucket: 'shopping-app-final-k23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKWdbeqtiiPzKN3rs5bagy1OKisFI5Zko',
    appId: '1:292385856722:ios:403fe1b4f19e802465610b',
    messagingSenderId: '292385856722',
    projectId: 'shopping-app-final-k23',
    storageBucket: 'shopping-app-final-k23.firebasestorage.app',
    iosClientId: '292385856722-k30ro4v5tfarolgq4a3b0tnjs25e1de8.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingAdminFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKWdbeqtiiPzKN3rs5bagy1OKisFI5Zko',
    appId: '1:292385856722:ios:403fe1b4f19e802465610b',
    messagingSenderId: '292385856722',
    projectId: 'shopping-app-final-k23',
    storageBucket: 'shopping-app-final-k23.firebasestorage.app',
    iosClientId: '292385856722-k30ro4v5tfarolgq4a3b0tnjs25e1de8.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingAdminFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV2aaO45qelyp7CgCC1FZqO-DZl0RcRmg',
    appId: '1:292385856722:web:694bc601dee383cb65610b',
    messagingSenderId: '292385856722',
    projectId: 'shopping-app-final-k23',
    authDomain: 'shopping-app-final-k23.firebaseapp.com',
    storageBucket: 'shopping-app-final-k23.firebasestorage.app',
  );
}
